services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001' 
      - '3000:3000' 
    environment:    
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    restart: always

